docker:
  postgres:
    container: sample-go
    image: postgres:15-alpine

database:
  driver: postgres
  engine: postgresql
  name: simple_db
  ssl_mode: disable

  username: postgres
  password: 1202

  host: localhost
  port: 5432

server:
  host: localhost
  port: 8080

redis:
  host: 0.0.0.0
  port: 6379

token:
  secret_key: 12345678901234567890123456789012
  exp_duration: 15m

email:
  sender_name: Riadul Islam
  sender_address: dev.riadul@gmail.com
  sender_password: chxp aktf inqm zwwb
  exp_duration: 5m