version: '3'

services:
  redis:
    image: redis:7.2.1
    ports:
      - '6379:6379'

  postgres:
    container_name: sample-go
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1202
    ports:
      - '5432:5432'
